export const NOTIFICATION_RECIPIENT_TYPES = [
  "STUDENT",
  "PARENT",
  "CURRENT_APPROVER",
  "PREVIOUS_APPROVER",
  "ALL_APPROVERS",
  "WARDEN",
  "POC",
  "ADMIN",
  "HOSTEL_ADMIN",
  "SUPER_ADMIN",
] as const;

export type NotificationRecipientType =
  (typeof NOTIFICATION_RECIPIENT_TYPES)[number];

export const NOTIFICATION_RECIPIENT_TYPE = {
  STUDENT: "STUDENT",
  PARENT: "PARENT",
  CURRENT_APPROVER: "CURRENT_APPROVER",
  PREVIOUS_APPROVER: "PREVIOUS_APPROVER",
  ALL_APPROVERS: "ALL_APPROVERS",
  WARDEN: "WARDEN",
  POC: "POC",
  ADMIN: "ADMIN",
  HOSTEL_ADMIN: "HOSTEL_ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
} as const;
