export const NOTIFICATION_EVENTS = [
	"LEAVE_SUBMITTED",
	"LEAVE_APPROVED",
	"LEAVE_REJECTED",
	"LEAVE_CANCELLED",
	"LEAVE_COMPLETED",
	"LEAVE_EXPIRED",
	"LEAVE_EXTENSION_REQUESTED",
	"LEAVE_EXTENSION_APPROVED",
	"LEAVE_EXTENSION_REJECTED",
	"LEAVE_OVERDUE",
	"PARENT_APPROVAL_REQUESTED",
	"LEAVE_APPROVAL_REQUIRED",
	"LEAVE_POC_REVIEW_REQUIRED",
	"LEAVE_QUESTION_ASKED",
	"QR_GENERATED",
	"QR_SCANNED",
	"QR_INVALIDATED",
	"LATE_STAY_AUTH_SUBMITTED",
	"LATE_STAY_AUTH_STEP_APPROVED",
	"LATE_STAY_AUTH_ACTIVE",
	"LATE_STAY_AUTH_REJECTED",
	"LATE_STAY_AUTH_REVOKED",
	"LATE_STAY_AUTH_EXPIRED",
] as const;

export type NotificationEvent =
	(typeof NOTIFICATION_EVENTS)[number];

export const NOTIFICATION_EVENT = Object.fromEntries(
	NOTIFICATION_EVENTS.map((e) => [e, e]),
) as Record<NotificationEvent, NotificationEvent>;
