export const OUTBOX_EVENT_TYPES = [
  "LEAVE_CREATED",
  "LEAVE_APPROVED",
  "LEAVE_REJECTED",
  "LEAVE_CANCELLED",
  "LEAVE_COMPLETED",
  "LEAVE_EXPIRED",
  "LEAVE_EXTENDED",
  "LEAVE_EXTENSION_APPROVED",
  "LEAVE_EXTENSION_REJECTED",
  "QR_GENERATED",
  "QR_SCANNED",
  "MOVEMENT_RECORDED",
  "NOTIFICATION_REQUESTED",
  "PARENT_APPROVAL_REQUIRED",
] as const;

export type OutboxEventType =
  (typeof OUTBOX_EVENT_TYPES)[number];

export const OUTBOX_EVENT_TYPE = {
  LEAVE_CREATED: "LEAVE_CREATED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",
  LEAVE_CANCELLED: "LEAVE_CANCELLED",
  LEAVE_COMPLETED: "LEAVE_COMPLETED",
  LEAVE_EXPIRED: "LEAVE_EXPIRED",
  LEAVE_EXTENDED: "LEAVE_EXTENDED",
  LEAVE_EXTENSION_APPROVED: "LEAVE_EXTENSION_APPROVED",
  LEAVE_EXTENSION_REJECTED: "LEAVE_EXTENSION_REJECTED",
  QR_GENERATED: "QR_GENERATED",
  QR_SCANNED: "QR_SCANNED",
  MOVEMENT_RECORDED: "MOVEMENT_RECORDED",
  NOTIFICATION_REQUESTED: "NOTIFICATION_REQUESTED",
  PARENT_APPROVAL_REQUIRED: "PARENT_APPROVAL_REQUIRED",
} as const;
