export const MOVEMENT_EVENTS = [
	"LEAVE_APPROVED",
	"EXIT_HOSTEL",
	"ENTER_HOSTEL",
	"AUTO_OVERDUE",
	"MANUAL_RETURN",
	"MANUAL_CHECKOUT",
	"SECURITY_OVERRIDE",
	"QR_INVALIDATED",
] as const;

export type MovementEvent =
	(typeof MOVEMENT_EVENTS)[number];

export const MOVEMENT_EVENT = {
	LEAVE_APPROVED: "LEAVE_APPROVED",
	EXIT_HOSTEL: "EXIT_HOSTEL",
	ENTER_HOSTEL: "ENTER_HOSTEL",
	AUTO_OVERDUE: "AUTO_OVERDUE",
	MANUAL_RETURN: "MANUAL_RETURN",
	MANUAL_CHECKOUT: "MANUAL_CHECKOUT",
	SECURITY_OVERRIDE: "SECURITY_OVERRIDE",
	QR_INVALIDATED: "QR_INVALIDATED",
} as const;
