export const AUDIT_ENTITY_TYPE = {
  LEAVE_REQUEST: "LEAVE_REQUEST",
  LEAVE_EXTENSION: "LEAVE_EXTENSION",
  LEAVE_APPROVAL: "LEAVE_APPROVAL",
  QR_PASS: "QR_PASS",
  MOVEMENT_EVENT: "MOVEMENT_EVENT",
  POLICY: "POLICY",
  USER: "USER",
  STUDENT: "STUDENT",
} as const;

export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPE)[keyof typeof AUDIT_ENTITY_TYPE];