"use client";

import { useState } from "react";

import { Loader2, QrCode } from "lucide-react";

import { QrCodeDisplay } from "@/components/qr/QrCodeDisplay";
import { ErrorState } from "@/components/shared/ErrorState";
import { InfoCard } from "@/components/shared/InfoCard";
import { LoadingState } from "@/components/shared/LoadingState";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/button";
import type { StudentDashboardStats } from "@/dto/dashboard/dashboard-stats.dto";
import { useDashboardStats } from "@/features/dashboard/hooks/use-dashboard-stats";
import { useCurrentUser } from "@/hooks/use-current-user";
import { useQrToken } from "@/hooks/use-qr-token";
import { generateQr, invalidateQr } from "@/lib/api/movement-api";

export default function StudentQRPage() {
  const { userId } = useCurrentUser();
  const { stats, isLoading, isError, error, mutate } = useDashboardStats();
  const { getTokenByLeaveId, storeToken } = useQrToken();
  const [generating, setGenerating] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);

  const s = stats as StudentDashboardStats | null;
  const activeLeave = s?.activeLeave ?? null;
  const activeQr = s?.activeQr ?? null;

  // Token stored in sessionStorage only — not in the database
  const qrToken = activeLeave?.id
    ? getTokenByLeaveId(activeLeave.id)
    : null;

  const handleGenerate = async () => {
    if (!activeLeave || !userId) return;
    setGenerating(true);
    setGenerateError(null);
    try {
      const result = (await generateQr(activeLeave.id, "LEAVE_EXIT")) as {
        passId: string;
        token: string;
      } | null;
      if (result?.passId && result?.token) {
        storeToken(result.passId, result.token, activeLeave.id);
      }
      await mutate();
    } catch (err) {
      setGenerateError(
        err instanceof Error ? err.message : "Failed to generate QR",
      );
    } finally {
      setGenerating(false);
    }
  };

  if (isLoading) return <LoadingState count={3} />;
  if (isError)
    return (
      <ErrorState
        message={error?.message ?? "Failed to load"}
        onRetry={() => mutate()}
      />
    );

  return (
    <div className="space-y-6">
      <PageHeader
        title="QR Pass"
        description="Generate and manage your QR exit/entry passes."
      />

      <div className="grid gap-6 lg:grid-cols-2">
        {/* QR Code Display */}
        <div className="rounded-2xl border border-border bg-card p-6 shadow-sm">
          <h3 className="mb-4 text-base font-semibold">Your QR Pass</h3>
          {activeQr && qrToken ? (
            <div className="flex flex-col items-center space-y-4">
              <QrCodeDisplay token={qrToken} size={240} />
              <div className="w-full space-y-2">
                <InfoCard
                  label="Status"
                  value="ACTIVE"
                  className="border-emerald-500/30"
                />
                {activeQr.expiresAt && (
                  <p className="text-center text-xs text-muted-foreground">
                    Valid until:{" "}
                    {new Date(activeQr.expiresAt).toLocaleString()}
                  </p>
                )}
              </div>
              <p className="text-center text-xs text-muted-foreground">
                Show this QR code at the security gate to exit the hostel.
              </p>
            </div>
          ) : activeQr && !qrToken ? (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <QrCode className="mb-4 h-10 w-10 text-muted-foreground/50" />
              <p className="mb-2 text-sm font-medium">Pass Active — Token Unavailable</p>
              <p className="mb-4 text-xs text-muted-foreground">
                Your token was lost (session expired). Regenerate a new pass to
                display the QR code.
              </p>
              <Button
                variant="default"
                disabled={regenerating}
                onClick={async () => {
                  if (!activeLeave?.id || !activeQr?.passId) return;
                  setRegenerating(true);
                  setGenerateError(null);
                  try {
                    await invalidateQr(activeQr.passId, "Regenerated by student");
                    const result = (await generateQr(
                      activeLeave.id,
                      "LEAVE_EXIT",
                    )) as { passId: string; token: string } | null;
                    if (result?.passId && result?.token) {
                      storeToken(result.passId, result.token, activeLeave.id);
                    }
                    await mutate();
                  } catch (err) {
                    setGenerateError(
                      err instanceof Error
                        ? err.message
                        : "Failed to regenerate QR pass",
                    );
                  } finally {
                    setRegenerating(false);
                  }
                }}
                className="gap-1.5"
              >
                {regenerating ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Regenerating...
                  </>
                ) : (
                  <>
                    <QrCode className="h-4 w-4" />
                    Regenerate Pass
                  </>
                )}
              </Button>
              {generateError && (
                <div className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">
                  {generateError}
                </div>
              )}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <div className="mb-4 rounded-xl bg-muted/50 p-6">
                <QrCode className="h-10 w-10 text-muted-foreground/50" />
              </div>
              <p className="text-sm text-muted-foreground">
                No active QR pass.
              </p>
              <p className="mt-1 text-xs text-muted-foreground">
                Generate a pass for your approved leave to exit the hostel.
              </p>
            </div>
          )}
        </div>

        {/* Generate / Info */}
        <div className="space-y-6">
          <div className="rounded-2xl border border-border bg-card p-6 shadow-sm">
            <h3 className="mb-4 text-base font-semibold">Generate New Pass</h3>
            {activeLeave ? (
              <div className="space-y-4">
                <div className="rounded-xl bg-muted p-4">
                  <p className="text-sm font-medium">
                    {activeLeave.leaveType}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    {new Date(activeLeave.startAt).toLocaleDateString()} →{" "}
                    {new Date(activeLeave.endAt).toLocaleDateString()}
                  </p>
                </div>

                {generateError && (
                  <div className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">
                    {generateError}
                  </div>
                )}

                <Button
                  onClick={handleGenerate}
                  disabled={generating || !!activeQr}
                  className="w-full"
                >
                  {generating ? (
                    <>
                      <Loader2 className="mr-1.5 h-4 w-4 animate-spin" />
                      Generating...
                    </>
                  ) : activeQr ? (
                    "Pass Already Active"
                  ) : (
                    "Generate QR Pass"
                  )}
                </Button>

                <p className="text-xs text-muted-foreground">
                  This will create an exit pass. After exiting, generate a
                  return pass to come back.
                </p>
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">
                You need an approved leave to generate a QR pass.
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
